### ISSUE TITLE
Solarpanels

### ISSUE THREAD

**Issue by bulletcather** [robertraaijmakers/com.iungo#16]
I have solarpanels connected on the Iungo.
The problem is that Iungo it counts a positive usages.
This result that is count in total enrgy of my house as use of power not as production.

Maybe if a device is a solar device the usage always is negative

**Comment by robertraaijmakers** [comment]
Hi,

Sorry for my awefull late reply. I don't have access to my Iungo and my Homey anymore. They were sold with the house. Probably when we move to a new house next summer I might get both again (and then I also have solar panels ;)).

What I thought what was implemented was the default energy usage in Homey. I modified some things for Homey energy and I think that the "positive" is counted as negative in Homey because it is of type solar. You should see that in the Homey Energy app.

If the issue still persists. Can you make some screenshots of the values you mean and also some screenshots of the Homey Energy view?

**Comment by robertraaijmakers** [comment]
Closed due to inactivity.
