### ISSUE TITLE
Modbus integration

### ISSUE THREAD

**Issue by jan-dico** [robertraaijmakers/com.iungo#20]
This is not an issue but I did not find an other way to address this question;
Having a lot of smart-home standalone solutions I am going to buy a Homy-Pro . I do have an Iungo for 10 years (including data) connected to 3 Modbus devices (each measuring a different solar panel string). In the description I did not notice the mod-bus support in your Iungo-app is this correct? In case you do not support these 3 Modbus what would be you advice to integrate our RS485 solar-energy measurements?

**Comment by robertraaijmakers** [comment]
Hi @jan-dico,

I have no experience with the RS485. It looks like a generic component that can handle all sorts of data.
The Iungo app is reading data from the Iungo API and not so much integrating with the devices. So as long as the data that the RS485 is generating is available in the API it can be incorporated in the Iungo App for Homey.

What kind of data is the RS485 generating and how does it look in the API? And also, what data would you like to see back in the Homey app?

**Comment by jan-dico** [comment]
Thanks Robert for your reply!
Iungo is only capable of handling 1 breakoutbox. An other way for Iungo to register kWk measurements is by the modus both for consumption and delivery (e.g. solar).
The modus is a kind of serial connection where each modus (identified by a modus number) send its value’s over the bus and is read by Iungo

In the Iungo app you can set by modus number if it is delivery or consumption device (see below number 2, 3 and 4 our 3 solar panel strings; the “functie” field is the type of device I described.
Bottomline the values are in the Iungo and my question is are they transferred/accessible using your Homey-pro app in the Homy App (to be integrated with consumption devices connected ted two the Homy-Pro system.




If your app is integrated using the basic data output capabilities I assume it is supported (the values look identical to the breakout-box but are only named according the modus-devicename as mentioned above by the field “Naam”.
In case you need access to my Iungo system to validate if your app will work  I am happy to open my remote access and send you a userid/password.
Warm regards Jandino.

**Comment by jan-dico** [comment]
You might have a look at the “control” output of Iungo to see the 3 modbus fields of the solar panels\

**Comment by robertraaijmakers** [comment]
My Homey and Iungo are currently in storage and not accessible. Can you send a sample output of your Iungo API with the devices? And maybe also line-out what to do with the values (e.g. should they be seperate meters on the device view in Homey, or should they be combined?). Then I might be able to do something with it and sent you a test version.

**Comment by jan-dico** [comment]
Hi Robert,
Background/line -out the purpose:
As stated in my initial request I am in process of selecting/buying a Homey-Pro and investigating if all my single point "Smart” solutions can be integrated in this single solution and assist us in better automate/utilise our electricity. Homey-Po is considered as it is an off the shelf solution with a large app portfolio. I do manage several Raspberry-Pi systems for SSL-terminatiting / portal in our Secure subnet and an other for our webservers in the server network so you understand my other option is Pi base. However I am hesitating for all the integration and maintenance effort; I am able to do some programming but certainly not a real programmer and stability/availability is key for the smart-home solution….
Would you be so kind to explain why your Homy and Iungo devices are stored; did you migrate to an other smart-home solution and why? Reading all the internet communities of the different solutions I noticed a lot of the early adapters and app developers of Homey have moved to different solutions…..

Energy is one of the most important subjects of our to-be smart-home solution (3 families and an office/company living on a single premises utilising a single connection for electricity (3 fase-low power) and gas.
Gas will be replaced by electricity in the next 4 to 5 years so managing electricity usage with respect to solar delivery and max provider connection (fuse limit of the connection) is more and more important (key!) As there is a real need to need to monitor each phase separately we need and manage the values of each Solar panel string (= phase) together with the demand per fase.

I am really happy with your offer to have a look to enable the modbus values in your app! But let us wait a few weeks until we do decide for Homey-Pro.
Warm regards Jandico

**Comment by robertraaijmakers** [comment]
Hi @jan-dico,

If energy reading and steering is the end-goal then Homey is probably not going to be the best option. If you are really into that then you should go for one of the dedicated solutions. In Belgium they have some nice start-ups that are working on solutions that monitor your energy production, consumption and also take the weather forecast into account to predict if you are going to need energy from the grid or are going to deliver it yourself. They are also working together with heat pumps, energy storage solutions, boilers etc. These are solutions build for steering and doing some predective analytics to get the most optimal energy consumption.

With regards to Homey, you can, of course, program a lot yourself and make some nice flows. You can also monitor quite a lot depending on what devices you have linked to your Iungo. For instance, see this bug here #21 (image: https://i.postimg.cc/bJKjnd0t/Knipsel.png). This guy is monitoring with Homey a lot of different devices/power groups. And it is all visible with the Iungo for Homey app.

And with regards to my Homey and Iungo being in storage. I sold my house a couple of months ago with the Homey integrated. The Iungo is actually in storage. But in my new home I will probably go for the Homey pro. I have been an early adopter and when you stick to solid protocols (like Z-Wave) and don't go for unsecure one-way protocols like 443, IR etc. then it is a fine product with a lot of possibilities. The only thing I might not want to go for Homey but for another solution (but don't know which one that would be) is because of the fact that Homey can't be linked via UTP to my network but has to operate wireless, and I really don't like wireless connections :)

Hope that helps!

**Comment by jan-dico** [comment]
Robert,
Thanks for your detailed explanation and advice, really appreciated.
I definately will investigate in who the Belgium start-up’s are and the status. Hopefully it support also my other smart-solution “investments” otherwise I can still add the Homey-pro to integrate the old stuff, however you created a warning for 443…..

I was also preferring UTP for critical services, now I have migrated to a business class of network with high bandwidth and stable WIFI I don’t mind some services to be WIFI attached. Security is of more importance to me; smart-home services, utilizing/integrating IOT, will not be allowed in my server network and I do not consider critical. This is why I expect finally will need two Smart-Home services for our homes and office. 

Thanks again for your assistance!
Warm regards Jandico
