### ISSUE TITLE
Wil connect to homey pro 2023 does not show values

### ISSUE THREAD

**Issue by ronennieshow** [robertraaijmakers/com.iungo#25]
Just as the title

I have connected my homey pro 2023 to the iungo 
But i only see the energy, solar pictograms 
There ar no value's vissable in it. 

I have restart the app 
I have restart the homey pro 2023
Even have tried to remove and reinstal the app
Stil the same issue

When i use the same app on the homey 2019 it works like a charm 

This is the values on the homey pro 2023
<img width="176" alt="image" src="https://user-images.githubusercontent.com/113858484/225703847-1b90a6b7-d433-4a2a-9f0c-fba2b33da510.png">

This is what i can see on the old homey 2019
<img width="182" alt="image" src="https://user-images.githubusercontent.com/113858484/225704262-b0298640-7417-413b-ad38-f937ffbc38b0.png">

**Comment by robertraaijmakers** [comment]
I see some more issues coming in (also on other apps) with the Homey Pro '23 version. I don't know what they did with the Homey Pro '23 that breaks some of the existing apps but I'm afraid that I can't help now because I don't own a Homey Pro '23 version and can't debug it to see why it doesn't work.

**Comment by ronennieshow** [comment]
Is there a way i can help you

I have a homey 2023 pro and willing to help

**Comment by robertraaijmakers** [comment]
Absolutely, I don't know how good your dev skills are :) but you can clone this repository (beta branch) and try to run the app in debug mode on your Homey via the developer tools to see if any specific errors pop-up.

https://tools.developer.homey.app/

**Comment by ronennieshow** [comment]
Poah. don't know how well my skils are.
But willing to try

Or otherwhise maybe a remote desktop is an option.

**Comment by bulletcather** [comment]
> Absolutely, I don't know how good your dev skills are :) but you can clone this repository (beta branch) and try to run the app in debug mode on your Homey via the developer tools to see if any specific errors pop-up.
> 
> https://tools.developer.homey.app

> Absolutely, I don't know how good your dev skills are :) but you can clone this repository (beta branch) and try to run the app in debug mode on your Homey via the developer tools to see if any specific errors pop-up.
> 
> https://tools.developer.homey.app/

How do you run a app in debug mode.

**Comment by bulletcather** [comment]
The app only works if you have a backup from a old Homey.
But if i do this my new Homey crashes.

**Comment by ronennieshow** [comment]
i have run a diagnostic rapport 0941a363-352a-443a-978e-3f8886bb0680

**Comment by robertraaijmakers** [comment]
Thanks, I have checked the report and nothing odd shows up. Actually, it seems to run perfectly fine refreshing the data values... 
It might have to do that it's either the Homey Pro 2023 or the fact that you are running version 10.0.0-rc.61 and that something major has changed in that version. I'm not in the RC channel so I cannot verify that latest hypothesis. Maybe you can check with Homey developers themselves as I can see that more apps have issues with the Homey Pro 2023, so maybe they know what the trigger for that is.

**Comment by ronennieshow** [comment]
Thanks for looking in to it so fast. 

Sow i will start updating the homey pro 2023 and maybe it solved.

**Comment by roko14** [comment]
I am also user of Homey Pro 2023, and unfortunately i also don't see any data.
Just to inform you, the update of the app to 1.0.3 did not fix this.
Hopefully there will be a solution soon....

**Comment by michelfrelink** [comment]
Hi All

Just curious if anybody has a solution for this in meanwhile? Having same issue with latest Homey 2023 firmware and new iungo.

thanks!

**Comment by roko14** [comment]
Athom could not help me..... 

They wrote:
("Thank you for reporting this issue.

Unfortunately, this issue concerns an app that is not developed by us, but by one of our valued community developers.
You can contact the developer of this app via the Homey App Store. Please contact him so he is aware of your reported issue.".)

So i really hope someone with the HP2023 can help finding a solution.
I would like to use Iungo together with Power By The Hour, but now this is useless....

**Comment by bulletcather** [comment]
You can still use mqtt with iungo.
This is what i do now.
If you want help with this let me know

Sent from Nine<http://www.9folders.com/>
________________________________
Van: roko14 ***@***.***>
verzonden: zondag 21 mei 2023 13:17
Aan: robertraaijmakers/com.iungo
Cc: bulletcather; Comment
Onderwerp: Re: [robertraaijmakers/com.iungo] Wil connect to homey pro 2023 does not show values (Issue #25)


Athom could not help me.....

They wrote:
("Thank you for reporting this issue.

Unfortunately, this issue concerns an app that is not developed by us, but by one of our valued community developers.
You can contact the developer of this app via the Homey App Store. Please contact him so he is aware of your reported issue.".)

So i really hope someone with the HP2023 can help finding a solution.
I would like to use Iungo together with Power By The Hour, but now this is useless....

**Comment by michelfrelink** [comment]
Hi bulletcather

Would be interested to try mqtt, which app and setup are you using?

BR Michel

**Comment by bhollenberg** [comment]
Morning Gents,

Since yesterday I am also the proud owner of a Homey Pro 2023. I myself have been using Iungo for 7 years (consumption of electricity, gas, inverters for solar panels, water meter and monitoring car charging station) and I try to link it to HP2023, but as others have indicated above, the values ​​are not showed in HP2023. The switches/wall plugs do respond to an on/off command, but unfortunately also do not display any consumption values. 

Is there a working fix available?

**Comment by bulletcather** [comment]
You can still use mqtt with iungo.
________________________________
Van: bhollenberg ***@***.***>
Verzonden: donderdag 22 juni 2023 07:58
Aan: robertraaijmakers/com.iungo ***@***.***>
CC: bulletcather ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [robertraaijmakers/com.iungo] Wil connect to homey pro 2023 does not show values (Issue #25)


Morning Gents,

Since yesterday I am also the proud owner of a Homey Pro 2023. I myself have been using Iungo for 7 years (consumption of electricity, gas, inverters for solar panels, water meter and monitoring car charging station) and I try to link it to HP2023, but as others have indicated above, the values ​​are not showed in HP2023. The switches/wall plugs do respond to an on/off command, but unfortunately also do not display any consumption values.

Is there a working fix available?

**Comment by roko14** [comment]
I don't want to use mqtt.
The app is working fine with all Homey Pro, exept the new HP2023. What is the reason?
The developer can find out why, we can't. I really hope the developer can change the app so it will also work with the HP2023...

**Comment by robertraaijmakers** [comment]
I’m sorry, I can’t figure out why. I developed the app according to all Athom best practices. I don’t own the new Homey pro and absolutely not on the planning to buy one, investing €400 to maintain an app is not worth it for me, sorry…

**Comment by ronennieshow** [comment]
I do not know where you are from. 
But if you like you can have a look at my homey. 

Willing to help. 
Must be some small and easy issue

**Comment by Marsattacks12** [comment]
Same issue here. No data shown on HP2023. Only   static energy cost values are shown in settings (so there is some sort of connection)

**Comment by DionvanHulst** [comment]
@robertraaijmakers , I ran the beta app on Homey Pro 2023 in developer mode as mentioned above and attached the debug log.

[Iungo_debug_run.txt](https://github.com/robertraaijmakers/com.iungo/files/11909740/Iungo_debug_run.txt)

on _refreshDevices it gets a _syncDevice and than an 'undefiend'. this is the point where I would expect to get values.
Can you check and/or give hints to continue debugging / where to look further?

**Comment by robertraaijmakers** [comment]
Thanks for the log, it gives some point of direction. However, can't find anything strange in the class. When I have some time again I will try to add some extra log lines in that specific class (energy_meter/device.js , function syncDevice) and then maybe somebody can run it again and we can try to narrow it down.

However, I still really think it is somewhere an issue in the Homey software itself, but we will see if we can narrow it down and then go to Athom and see if they can fix it :)

**Comment by DionvanHulst** [comment]
Hello

I did some debugging, and have found the following:

Within the function 'syncDevice()' in device.js
The 'deviceState' remains empty/null. 
  I believe this might be due to thate there is no function ref to 'getState'.

When changing for( let capabilityId in deviceState ) to for( let capabilityId in deviceInstance )
The 1st execution of _refreshDevices gives debug logs with 'sync value' and a value
After the valid capabilityId's run out a lot of errors (ignore for now)
Also the 'undefined' gives 'undefined' responses

the 2nd execution of _refreshDevices does give a valid deviceState wiht values.
the for loop runs as above,.

File: [Iungo_debug_changedForLoop1.txt](https://github.com/robertraaijmakers/com.iungo/files/11927091/Iungo_debug_changedForLoop1.txt)

changed for( let capabilityId in deviceInstance ) to for( let capabilityId in deviceState )
I kept the device (only app got removed, device status was app unavailable)

Ran app again, values are being updated in the device.

File: [Iungo_debug_changedbackForLoop.txt](https://github.com/robertraaijmakers/com.iungo/files/11927093/Iungo_debug_changedbackForLoop.txt)

![Screenshot_20230701_224020_Homey](https://github.com/robertraaijmakers/com.iungo/assets/138159784/c2ebb5ff-21e5-4d8c-8bf9-8511c3587c60)


I tried the steps above on the 'energy solar' device as well,
The deviceState gets filled and the values are updated in the device.


My conclusion for now.
Upon first install the deviceStatus does not get initialized properly, therfore the syncDevice function does not get into the update for loop

@robertraaijmakers , hopefully I pointed you into the right direction to solving this issue

**Comment by robertraaijmakers** [comment]
This should be possible to fix! Will have a look (hopefully I have some time this weekend) :)

**Comment by robertraaijmakers** [comment]
Anyone willing to test a new version: https://homey.app/nl-nl/app/com.iungo/Iungo/test/ ? :)

**Comment by bhollenberg** [comment]
> Anyone willing to test a new version: https://homey.app/nl-nl/app/com.iungo/Iungo/test/ ? :)

At first glance it seems to work! 😃

**Comment by ronennieshow** [comment]
Yes. The new beta is working 
I am getting values true

**Comment by Marsattacks12** [comment]
> Anyone willing to test a new version: https://homey.app/nl-nl/app/com.iungo/Iungo/test/ ? :)

Tnx Robert. It works from the get go

**Comment by michelfrelink** [comment]
Bedankt Robert! Werkt prima nu 😃

**Comment by robertraaijmakers** [comment]
That's great to hear! Have submitted the app for certification, will be available in the public channels soon.
